#! /bin/bash

export GUIDES=(
    "install-guide"
    "user-guide"
)

export REPOS=(
	"github.com/ossimlabs/omar-common.git"
	"github.com/radiantbluetechnologies/isa-ui.git"
	"github.com/ossimlabs/omar-admin-server.git"
	"github.com/ossimlabs/omar-avro-metadata.git"
	"github.com/ossimlabs/omar-base.git"
	"github.com/ossimlabs/omar-basemap.git"
	"github.com/ossimlabs/omar-cmdln.git"
	"github.com/ossimlabs/omar-config-server.git"
	"github.com/ossimlabs/omar-disk-cleanup.git"
	"github.com/ossimlabs/omar-download.git"
	"github.com/ossimlabs/omar-eureka-server.git"
	"github.com/ossimlabs/omar-geoscript.git"
	"github.com/ossimlabs/omar-jpip.git"
	"github.com/ossimlabs/omar-mapproxy.git"
	"github.com/ossimlabs/omar-mensa.git"
	"github.com/ossimlabs/omar-oms.git"
	"github.com/ossimlabs/omar-ossim-base.git"
	"github.com/ossimlabs/omar-sqs-stager.git"
	"github.com/ossimlabs/omar-mapproxy.git"
	"github.com/ossimlabs/omar-basemap.git"
	"github.com/ossimlabs/omar-stager.git"
	"github.com/ossimlabs/omar-superoverlay.git"
	"github.com/ossimlabs/tlv.git"
	"github.com/ossimlabs/omar-turbine-server.git"
	"github.com/ossimlabs/omar-twofishes.git"
	"github.com/ossimlabs/omar-ui.git"
	"github.com/ossimlabs/omar-wcs.git"
	"github.com/ossimlabs/omar-web-proxy.git"
	"github.com/ossimlabs/omar-wfs.git"
	"github.com/ossimlabs/omar-wms.git"
	"github.com/ossimlabs/omar-wmts.git"
	"github.com/ossimlabs/omar-zipkin-server.git"
	"github.com/radiantbluetechnologies/ossim-isa.git"
	"github.com/ossimlabs/rhel-minimal.git"
)
