#! /bin/bash

export GUIDES=(
    "install-guide"
    "user-guide"
)

export REPOS=(
	"github.com/ossimlabs/omar-common.git"
	"github.com/radiantbluetechnologies/isa-ui.git"
	"github.com/ossimlabs/omar-avro.git"
	"github.com/ossimlabs/omar-avro-metadata.git"
	"github.com/ossimlabs/omar-base.git"
	"github.com/ossimlabs/omar-config-server.git"
	"github.com/ossimlabs/omar-geoscript.git"
	"github.com/ossimlabs/omar-disk-cleanup.git"
	"github.com/ossimlabs/omar-download.git"
	"github.com/ossimlabs/omar-eureka-server.git"
	"github.com/ossimlabs/omar-jpip.git"
	"github.com/ossimlabs/omar-mensa.git"
	"github.com/ossimlabs/omar-oms.git"
	"github.com/ossimlabs/omar-opir.git"
	"github.com/ossimlabs/omar-ossim-base.git"
	"github.com/ossimlabs/omar-service-proxy.git"
	"github.com/ossimlabs/omar-scdf-sqs.git"
	"github.com/ossimlabs/omar-scdf-downloader.git"
	"github.com/ossimlabs/omar-scdf-s3-filter.git"
	"github.com/ossimlabs/omar-scdf-s3-uploader.git"
	"github.com/ossimlabs/omar-scdf-extractor.git"
	"github.com/ossimlabs/omar-scdf-aggregator.git"
	"github.com/ossimlabs/omar-scdf-file-parser.git"
	"github.com/ossimlabs/omar-scdf-notifier-email.git"	
	"github.com/ossimlabs/omar-scdf-kafka.git"
	"github.com/ossimlabs/omar-scdf-server.git"		
	"github.com/ossimlabs/omar-scdf-zookeeper.git"		
	"github.com/ossimlabs/omar-scdf-stager.git"	
	"github.com/ossimlabs/omar-scdf-indexer.git"	
	"github.com/ossimlabs/omar-sqs.git"
	"github.com/ossimlabs/omar-mapproxy.git"
	"github.com/ossimlabs/omar-stager.git"
	"github.com/ossimlabs/omar-superoverlay.git"
	"github.com/ossimlabs/omar-turbine-server.git"
	"github.com/ossimlabs/omar-twofishes.git"
	"github.com/ossimlabs/omar-ui.git"
	"github.com/ossimlabs/omar-wcs.git"
	"github.com/ossimlabs/omar-web-proxy.git"
	"github.com/ossimlabs/omar-wfs.git"
	"github.com/ossimlabs/omar-wms.git"
	"github.com/ossimlabs/omar-wmts.git"
	"github.com/ossimlabs/omar-zuul-server.git"
	"github.com/radiantbluetechnologies/ossim-isa.git"
	"github.com/ossimlabs/rhel-minimal.git"
	"github.com/ossimlabs/tlv.git"
)
